name: Packer-Build Develop Server CI/CD

on:
  pull_request:
    branches: ["main", "dev"]
    paths: "packer/**"

jobs:
  packer_build:
    runs-on: ubuntu-20.04

    uses: ./.github/workflows/packer-build.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    - name: Terraform apply
      run: terraform apply