name: Terraform-Validation Develop Server CI/CD

on:
  push:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"
  pull_request:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_validation:
    uses: ./.github/workflows/terraform_validation.yml
