name: Terraform-Validation Production Server CI/CD

on:
  push:
    branches: ["main", "dev"]
    paths: "terraform/production/**"
  pull_request:
    branches: ["main", "dev"]
    paths: "terraform/production/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_validation:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/terraform_validation.yml
