name: Terraform-Validation Develop Server CI/CD

on:
  push:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"
  pull_request:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform_validation:
    runs-on: ubuntu-20.04

    - uses: actions/checkout@v2

    - name: Terraform Init & Validation
      uses: init-cloud/terraform-provisioning/.github/workflows/terraform_validation.yml@main
