name: Terraform-Validation Develop Server CI/CD

on:
  push:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"
  pull_request:
    branches: ["main", "dev"]
    paths: "terraform/dev/**"

jobs:
  terraform_validation:
    uses: ./.github/workflows/terraform-validation.yml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}